name = input("enter your name: ")
year =input("inter your brith year")
b_year = int(year)
year1 = input("please inter this year")
c_year = int(year1)
print(f"{name} you are {c_year-b_year} year old now")
